title = "Climbing Coder"
baseURL = "https://jholloc.github.io"
languageCode = "en-gb"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Jonathan Hollocombe"
  favicon = ""
  site_logo = "images/climbing coder-logos_white.png"
  description = "A coding blog."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  recent_posts_number = 3
  custom_css = ["custom.css"]
  mainSections = ["post", "test"]
  recent_copy = "Recent Posts"

[params.ananke_socials.1]
name = "twitter"
url = "https://twitter.com/JHollocombe"

[params.ananke_socials.2]
name = "github"
url = "https://github.com/jholloc"

[params.ananke_socials.3]
name = "linkedin"
url = "https://www.linkedin.com/in/jonathan-hollocombe-053b6a12/"
